### ISSUE TITLE
Allow to use `yml` for config file

### ISSUE THREAD

**Issue by FirelightFlagboy** [cempassi/taskmaster#23]
could be neat to allow configuration file to be written in `YAML`

```yml
- name: ls
  command: ls -l ~
  autostart: true
  numprocess: 1
  umask: 0222
  workingdir: /tmp
  stdout: /tmp/ls.out
  stderr: /tmp/ls.err
  stopsignal: TERM

- name: curl google
  command: curl www.google.com
  autostart: true
  env:
    FOO: bar
```
