### ISSUE TITLE
Better config

### ISSUE THREAD

**Issue by FirelightFlagboy** [cempassi/taskmaster#38]
will reading the doc (RTFM) of [toml - 0.5.8](https://docs.rs/toml/0.5.8/toml/) and how `value::Table` can help us to create a more pleasing configuration.

instead of writing the configuration like bellow:
```toml
[[task]]
name = "foo"
cmd = "echo foo"

[[task]]
name = "bar"
cmd = "echo bar"
```

we can write the configuration like bellow:
```toml
[foo]
cmd = "echo foo"

[bar]
cmd = "echo bar"
```
